version: "3.3"

services:
  flaskapp:
    image: "ghcr.io/arajput63/flask_socketio_example:${TAG-latest}"
    env_file:
      - .env
    ports:
      - "80:5000"
    build:
      context: ./
      dockerfile: Dockerfile
